- android/app/build.gradle
- android/app/google-services.json
- android/build.gradle
- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- ios/Runner/GoogleService-Info.plist
- lib/loginPage.dart
- lib/signUpPage.dart
- pubspec.lock
- pubspec.yaml
파이어베이스 연동 / 자동 로그인 구현
파이어베이스 auth 통한 회원가입, 로그인, 비밀번호 변경 가능
내부 데이터베이스 (shared_preferences) 이용한 자동로그인 기능 추가
회원가입시 이메일과 비밀번호를 제외한 다른 정보를 실시간데이터베이스에 저장할지, 파이어스토어에 저장할지 정해야함.
코드가 많이 지저분해져서 리팩토링 한번 해야함
> connect firebase, add autologin

- lib/managementPage.dart
- lib/registerPage.dart
- pubspec.lock
관리 페이지 등록 및 등록 페이지 디자인 수정
관리페이지 간단하게 파일만들고 등록페이지 디자인 수정
연결은 안되어있음
> 관리 페이지 생성 및 등록 페이지 디자인 수정

- lib/signUpPage.dart
회원가입 페이지 주민번호 수정 및 autofocus 추가
앞자리와 뒷자리 분리, 앞자리 입력후 자동으로 뒷자리 autofocus
> 회원가입 페이지 주민번호 수정 및 autofocus 추가

- lib/main.dart
- lib/reportPage.dart
보고서 작성 페이지 
보고서 작성 페이지 디자인, 데이터 저장 부분 제외하고 레이아웃 구성 완료
어디서 라우트 되는지 몰라서 페이지만 만듬, 데이터를 저장하는 부분은 더 해야함
> add report page

- lib/components/customAppBar.dart
- lib/main.dart
- lib/mainPage.dart
바텀 네브바 애니메이션 고정 및 페이지 네비게이팅 연결
바텀 네브바 애니메이션이 일어나지 않도록 변경하였고 코드를 단순하게 리팩토링하였다
Register Page로 이동이 불가능하다
> add color and navigator in btn Navbar

- lib/components/customAppBar.dart
- lib/mainPage.dart
로그아웃 버튼 추가 + 보고서 페이지로 넘어가는 아이콘에 버튼 추가
로그아웃을 할 수 있는 버튼을 메인 페이지에 추가하였고 보고서 페이지로 넘어갈 수 있는 버튼을 아이콘에 입혔습니다
로그아웃이 실제로 되는 기능은 아직 구현하지 않음
> add logout button and report page button

- lib/mainPage.dart
- lib/reportPage.dart
로그아웃 기능 구현
자동로그인 취소되며 로그아웃되게 구현
> add logout

- lib/components/personal_card.dart
- lib/mainPage.dart
mainpage에 화살표만 버튼 효과
mainpage에 관리대상 리스트의 화살표만 버튼 효과
> add icon button to profile

- lib/components/customAppBar.dart
- lib/loginPage.dart
- lib/main.dart
- lib/signUpPage.dart
initialRoute 를 로그인 -> 커스텀 앱바
로그인 페이지 이후 커스텀 앱바
> 커스텀 앱바 라우트

- ios/Podfile.lock
- lib/signUpPage.dart
- pubspec.lock
- pubspec.yaml
생활관리사 계정 데이터베이스 연동
회원가입하면 파이어스토어 Accounts 컬렉션에 추가됨
> 회원가입 후 계정 데이터베이스 연동

- lib/components/report_card.dart
- lib/models/report.dart
- lib/reportListPage.dart
report 리스트 추가
사회복지사들이 추가해야 되는 report list를 추가했습니다
> Add report list

- lib/components/customAppBar.dart
- lib/settingPage.dart
설정 페이지 추가
알림설정, 개인정보, 앱정보 관련 영역추가 해서 틀만 만듬 세부 라우트는 결정되면 추가 예정
알림 기능 넣을건가
> add setting page

- lib/loginPage.dart
- lib/models/report.dart
- lib/reportListPage.dart
- lib/signUpPage.dart
전반적인 btn 스타일 수정 및 독거노인 리스트 수정
btn 사이즈를 조금 작게 수정해주고 독거노인별 리스트 페이지를 수정함
> Edit btn stlye & List view

- lib/components/report_card.dart
- lib/personalReportPage.dart
- lib/reportListPage.dart
개인별 report list 생성
개인별 report list를 생성하였고 이를 적용했음
전체 report list에서 개인별 report list로 가는 버튼이 제대로 작동하지 않음 / 수정 요망
> Add Personal report list

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
fix flutter run
충돌을 안고치고 push해버려서 고쳤습니다
> fix flutter run

- lib/components/report_card.dart
- lib/personalReportPage.dart
- lib/reportListPage.dart
Report list 수정
Report list에서 필요없는 부분들 제거 및 UI 수정
> edit report list

- android/.project
- android/.settings/org.eclipse.buildship.core.prefs
- android/app/.classpath
- android/app/.project
- android/app/.settings/org.eclipse.buildship.core.prefs
- ios/Podfile.lock
- lib/loginPage.dart
- pubspec.lock
- pubspec.yaml
로그인 페이지에서 메인 페이지로 라우트 될때 Replacement
메인페이지에서 로그인 페이지로 뒤로 못가게 변경
> login to main page route

- lib/loginPage.dart
자동 로그인으로 메인 페이지 라우트 
메인 페이지에서 뒤로가기 수정
> auto login fix

- lib/components/customAppBar.dart
- lib/mainPage.dart
> delete floating action button

- lib/mainPage.dart
- pubspec.lock
> add notification icon

- lib/components/customAppBar.dart
Edit icon in bottom App bar
바텀 앱바의 환결설정 아이콘을 그에 맞게 변환
> edit icon in bottom App bar

- lib/mainPage.dart
복지사 이름이 화면에 등장
파이어베이스에 있는 복지사 정보를 스냅샷으로 가져옴
> display 복지사 이름 

- lib/components/topAppBar.dart
- lib/mainPage.dart
- lib/personalReportPage.dart
- lib/reportListPage.dart
top App bar 만들기
바텀 앱바가 없는 곳에 앱바 추가용 앱바 생성
> Create top App bar

- ios/Podfile.lock
- lib/components/topAppBar.dart
- lib/mainPage.dart
- pubspec.lock
- pubspec.yaml
노인 리스트 메인 화면에 파이어베이스 연동
파이어베이스 상 ElderInfo 에 있는 노인들의 정보를 리스트뷰 스냅샷으로 정보를 가져옴
> connect Firebase Elders list

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/key.properties
- lib/components/customAppBar.dart
- lib/main.dart
- pubspec.lock
Firebase Cloud Messaging 추가 (안드로이드)  
안드로이드에서 푸쉬알림 연동 완료. (키스토어, SHA 확인 후 연동)
아이폰은 애플 개발자 등록 해야 APN 키 발급 가능
> add push notification (FCM)

- lib/secondRegistrerPage.dart
- pubspec.lock
delete stack of register pages
등록페이지 스택 쌓이는 거 한번에 삭제
> delete stack of register pages

- ios/Podfile.lock
- lib/components/alertPopup.dart
- lib/registerPage.dart
- lib/secondRegistrerPage.dart
register to firebase
등록하면 파이어베이스에 들어감
> register to firebase

- ios/Podfile.lock
- lib/alertListPage.dart
- lib/mainPage.dart
- pubspec.lock
> Create alert list

- lib/personalReportPage.dart
보고서 목록 연동
파이어베이스 보고서 목록 이름만 연동
> connect report List

- lib/main.dart
- lib/personalReportPage.dart
- lib/reportPage.dart
개인 보고서 페이지 연결 
개인 보고서 작성페이지 뒤로가기 버튼 추가 및 이름 자동완성 기능 추가
> connect personal report page

- ios/Podfile.lock
- lib/components/alertPopup.dart
- lib/components/report_card.dart
- lib/main.dart
- lib/personalReportPage.dart
- lib/reportListPage.dart
- lib/reportPage.dart
보고서 작성 페이지 파이어베이스에 연동
보고서 작성 후 파이어스토어에 set
개인 보고서 열람 페이지와 리스트 카드 위젯 만들어야함
> connect report page to firebase

- lib/components/personal_card.dart
- lib/components/report_card.dart
- lib/mainPage.dart
- lib/reportListPage.dart
- lib/reportPage.dart
맥박 지수 프로필에 연동, 보고서에 최근 업데이트 날짜 등록
프로필 카드에 맥박 지수 연동, 최근 업데이트 된 날짜 연동
맥박 지수가 하나밖에 없어 일단 기본값으로 연동
> add pulse value, latest report date

- lib/secondRegistrerPage.dart
image upload depends on size and extension
사이즈 크면 알림, 확장자 이름으로 저장
> image upload depends on size and extension

- lib/components/personal_card.dart
- lib/mainPage.dart
- lib/managementPage.dart
management page에 최신 보고서 날짜 추가
management page에 최신 보고서 날짜 추가
> add latest report to management page

- lib/components/alertPopup.dart
- lib/registerPage.dart
- lib/reportPage.dart
- lib/secondRegistrerPage.dart
add more alert popups
알림 종류 등록 형식마다 추가
> add more alert popups

- lib/components/personal_card.dart
- lib/mainPage.dart
- lib/managementPage.dart
- lib/models/profile.dart
modify management page's profile info
관리 페이지에 프로필정보 가져와서 보여주기
> modify management page's profile info

- lib/alertListPage.dart
- lib/mainPage.dart
새로운 알림 업데이트 및 알림 삭제 기능 추가
새로운 알림 발생시 메인 화면과 알림 목록에 업데이트, 알림 스와이프로 삭제 가능
> add notification list counting and deleting

- FCF/functions/index.js
FCF 사용하여 맥박 감지시 알림 목록에 저장하고 FCM 전송
FCF 로 맥박 log create 되면 알림 리스트에 추가되고 FCM으로 메시지 전송
부정맥 조건 넣어야함
> cloud function notification save

- lib/mainPage.dart
토큰 리스트에 자동으로 기기 토큰 추가
메인 페이지에서 계정에 기기 토큰 추가
> append token list

- lib/secondRegistrerPage.dart
사진등록시 비동기 처리로 사진 등록 완료후 페이지 pop
사진등록시 곧바로 pop되면 오류가 생겼으나 등록 완료후 비동기처리후 pop
한글이름 등록시 오류 발생
> async upload pic

- lib/secondRegistrerPage.dart
modify photo name to random number
사진이름을 날짜 년 월 일 시간 분 + 랜덤숫자 .확장자 로 바꿨음
> modify photo name to random number

- ios/Podfile.lock
- lib/components/report_card.dart
- lib/components/singleReport_card.dart
- lib/registerPage.dart
- lib/reportListPage.dart
- lib/reportPage.dart
- lib/secondRegistrerPage.dart
- lib/settingPage.dart
- lib/signUpPage.dart
> change to English

- lib/components/singleReport_card.dart
- lib/reportPage.dart
> Englishzation

- lib/reportPage.dart
- lib/signUpPage.dart
change more english considering padding
영어 짧게 줄임
> change more english considering padding

- lib/reportListPage.dart
> order by latest report

- lib/registerPage.dart
- lib/secondRegistrerPage.dart
change background color of register pages
등록 페이지 배경색 통일
> change background color of register pages

- FCF/functions/index.js
- lib/mainPage.dart
- lib/registerPage.dart
update pulse data
맥박 데이터 파이어베이스에 연동시 업데이트
> update pulse data

- README.md
- lib/components/customAppBar.dart
> Edit Readme file

- lib/components/personal_card.dart
- lib/components/report_card.dart
- lib/components/singleReport_card.dart
- lib/main.dart
- lib/mainPage.dart
- lib/managementPage.dart
- lib/reportPage.dart
- pubspec.lock
- pubspec.yaml
> fix size all

- lib/components/personal_card.dart
- lib/components/report_card.dart
- lib/components/singleReport_card.dart
- lib/main.dart
- lib/mainPage.dart
- lib/managementPage.dart
- lib/reportPage.dart
- pubspec.lock
- pubspec.yaml
Reverts DSCHUFS/DSC-Solution-Challenge-2020#80
> Revert "fix size all"
